### PR TITLE
Use store in modules mode.

### PR DESCRIPTION
**Pull request by smnscp**
#1

### CODE REVIEW

**Comment by smnscp** [comment]
I just realized that store/database.js should be moved out of the store directory. Otherwise Nuxt will create an empty state namespace “database”.
superfluous database namespace
I’d move it to orm/database.js.

**Comment by kiaking** [comment]
@smnscp Hi! thank you so much for this and so sorry for my late reply. I was thinking to do this too! One small favor, could you move database to `database` folder instead of `orm`?

**Comment by smnscp** [comment]
@kiaking Here you are! I’ve renamed that directory.
By the way, thank you very much for this project! Coming from the back-end side with all its strong ORM features I had been looking for something like this to manage entities in a clean way on the front-end, too. So I was quite amazed to find the Vue.js ecosystem to already have exactly what I needed.

**Comment by kiaking** [comment]
@smnscp Thanks a lot! And thank you so much for such a sweet comment. Thank YOU for finding out Vuex ORM and wonderful PR! 🎉

**Pull request merged**
